# Generated by Django 3.0.5 on 2024-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
