# Generated by Django 3.0.5 on 2024-07-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemo', '0002_auto_20240704_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='Empty', max_length=5),
        ),
    ]
