# Generated by Django 3.0.5 on 2024-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemo', '0003_auto_20240705_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
