# Generated by Django 3.0.5 on 2024-07-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hemo', '0004_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('total', models.FloatField()),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemo.hospital')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hemo.stock')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
